# This file was generated by GoReleaser. DO NOT EDIT.
cask "terratidy" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "dcb94fca4faf88c1979c21c3f8d4792d09d063669bfa005660804744199e0d20"
      url "https://github.com/santosr2/terratidy/releases/download/v#{version}/terratidy-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "30ab348afcd5529cf3e239dc922834ed93bc7439c793638dd7794b664271cda8"
      url "https://github.com/santosr2/terratidy/releases/download/v#{version}/terratidy-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4e292bfca138c459cbb7adfd7d51e00abf05bfe8bd7c5a24350dbb3d3b2f7d2"
      url "https://github.com/santosr2/terratidy/releases/download/v#{version}/terratidy-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "40de1c87010f3aea3a11a6c2eddbbece69ffd3c0f3ee1c2319580a27ea266419"
      url "https://github.com/santosr2/terratidy/releases/download/v#{version}/terratidy-#{version}-linux-arm64.tar.gz"
    end
  end

  name "terratidy"
  desc "Terraform/Terragrunt quality platform"
  homepage "https://github.com/santosr2/TerraTidy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terratidy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terratidy"]
    end
  end

  # No zap stanza required

end
